In [9]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

# ─────────────────────────────────────────────
# LOAD CLEANED DATA
# ─────────────────────────────────────────────
df = pd.read_csv("data_cleaned1.csv")  # update path as needed

print("Shape:", df.shape)
print("\nColumns:", df.columns.tolist())

Shape: (40004, 12)

Columns: ['heart_rate', 'respiratory_rate', 'body_temperature', 'oxygen_saturation', 'systolic_bp', 'diastolic_bp', 'age', 'gender', 'derived_hrv', 'derived_pulse_pressure', 'derived_bmi', 'risk_category']

In [10]:
X=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [3]:
pd.DataFrame(X).head()

,heart_rate,respiratory_rate,body_temperature,oxygen_saturation,systolic_bp,diastolic_bp,age,gender,derived_hrv,derived_pulse_pressure,derived_bmi
0,60,12,36.861707,95.702046,124,86,37,Female,0.121033,38,32.459031
1,63,18,36.511633,96.689413,126,84,77,Male,0.117062,42,12.771246
2,63,15,37.052049,98.508265,131,78,68,Female,0.053200,53,28.821069
3,99,16,36.654748,95.011801,118,72,41,Female,0.064475,46,28.554611
4,69,16,36.975098,98.623792,138,76,25,Female,0.118484,62,16.081438

In [11]:
le_gender = LabelEncoder()
X['gender'] = le_gender.fit_transform(X['gender'])

In [5]:
pd.DataFrame(X).head()

,heart_rate,respiratory_rate,body_temperature,oxygen_saturation,systolic_bp,diastolic_bp,age,gender,derived_hrv,derived_pulse_pressure,derived_bmi
0,60,12,36.861707,95.702046,124,86,37,0,0.121033,38,32.459031
1,63,18,36.511633,96.689413,126,84,77,1,0.117062,42,12.771246
2,63,15,37.052049,98.508265,131,78,68,0,0.053200,53,28.821069
3,99,16,36.654748,95.011801,118,72,41,0,0.064475,46,28.554611
4,69,16,36.975098,98.623792,138,76,25,0,0.118484,62,16.081438

In [12]:
# STEP 3: LABEL ENCODE risk_category (ordinal target)
risk_mapping = {
    "Low Risk"      : 0,
    "High Risk"     : 1
}

y_encoded = y.map(risk_mapping)
y_encoded.name = "risk_category"

print("\n--- After Label Encoding risk_category ---")
print(f"Mapping : {risk_mapping}")
print(f"Unique values: {sorted(y_encoded.unique().tolist())}")
print(y_encoded.value_counts().sort_index())


Mapping : {'Low Risk': 0,  'High Risk': 1}

--- After Label Encoding risk_category ---
Mapping : {'Low Risk': 0, 'High Risk': 1}
Unique values: [0, 1]
risk_category
0    18968
1    21036
Name: count, dtype: int64

In [13]:
pd.DataFrame(y_encoded).head()

   risk_category
0              1
1              1
2              0
3              1
4              1